SELECT GETDATE(), SYSDATETIME()

SELECT	GETDATE() , SYSDATETIME()

SELECT	YEAR(GETDATE()), MONTH(GETDATE()), DAY(GETDATE())

SELECT	DATEPART(YEAR, GETDATE()) AS 'YEAR',
		DATEPART(MONTH, GETDATE()) AS 'MONTH',
		DATEPART(DAY, GETDATE()) AS 'DAY',
		DATEPART(HOUR, GETDATE()) AS 'HOUR',
		DATEPART(MINUTE, GETDATE()) AS 'MINUTE',
		DATEPART(SECOND, GETDATE()) AS 'SECOND'

SELECT	DATEADD(DAY, -100, GETDATE()),
		DATEADD(MINUTE, 100, GETDATE())

SELECT	DATEPART(WEEKDAY, GETDATE())

SELECT	DATEDIFF(DAY, '1961-04-12', GETDATE()),
		DATEDIFF(HOUR, '1961-04-12', GETDATE())